version: "3.5"

services:
    influxdb:
        image: influxdb
        container_name: influxdb
        networks:
            - monitoring-network
        ports:
            - 8086:8086
        volumes:
           - ./influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro 
           - ./influxdb/db:/var/lib/influxdb
        command: influxd -config /etc/influxdb/influxdb.conf

    telegraf:
        image: telegraf
        container_name: telegraf
        depends_on:
            - influxdb
        environment: 
            - HOST_PROC=/host/proc
        networks:
            - monitoring-network
        volumes:
            - ./telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /proc:/host/proc:ro
    
    grafana:
        image: grafana/grafana
        container_name: grafana
        depends_on:
            - influxdb
        networks:
            - monitoring-network
        ports:
            - 3000:3000

networks:
    monitoring-network:
        driver: bridge
        name: monitoring-network
    